name: Publish NPM Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Clone repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Auto increase version
      - name: Bump version
        run: |
          npm version patch -m "release: v%s"

      # Push new version
      - name: Push changes
        run: |
          git push
          git push --tags

      # Publish to npm
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
